version: "1.0"

services:
  train:
    build:
      context: .
      dockerfile: src/train/Dockerfile
    container_name: ml_train
    volumes:
      - ./models:/app/models          
      - ./logs:/app/logs              
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"
