version: "1.0"

services:
  inference:
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    container_name: ml_inference
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./src/inference:/app/inference
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
